
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Exception Handling Header for MicroBlaze RISC-V Processor
*
*******************************************************************/

#ifndef RISCV_EXCEPTIONS_G_H
#define RISCV_EXCEPTIONS_G_H


#ifdef __cplusplus
extern "C" {
#endif


#define RISCV_EXCEPTIONS_ENABLED 1


#ifdef __cplusplus
}
#endif 

#endif


