#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definitions for bus frequencies */
#define XPAR_CPU_M_AXI_DP_FREQ_HZ 100000000
/******************************************************************/

/* Canonical definitions for bus frequencies */
/******************************************************************/

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_RISCV_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/


/* Definitions for peripheral MICROBLAZE_RISCV_0 */
#define XPAR_MICROBLAZE_RISCV_0_ADDR_SIZE 32
#define XPAR_MICROBLAZE_RISCV_0_ARCHID 0x0000000000000001
#define XPAR_MICROBLAZE_RISCV_0_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_RISCV_0_ASYNC_WAKEUP 3
#define XPAR_MICROBLAZE_RISCV_0_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_RISCV_0_BASE_VECTORS 0x0000000000000000
#define XPAR_MICROBLAZE_RISCV_0_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_RISCV_0_DADDR_SIZE 32
#define XPAR_MICROBLAZE_RISCV_0_DATA_SIZE 32
#define XPAR_MICROBLAZE_RISCV_0_DCACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_RISCV_0_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_0_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_RISCV_0_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_RISCV_0_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_RISCV_0_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_0_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_RISCV_0_DCACHE_VICTIMS 0
#define XPAR_MICROBLAZE_RISCV_0_DC_AXI_MON 0
#define XPAR_MICROBLAZE_RISCV_0_DEBUG_COUNTER_WIDTH 64
#define XPAR_MICROBLAZE_RISCV_0_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_RISCV_0_DEBUG_EVENT_COUNTERS 0
#define XPAR_MICROBLAZE_RISCV_0_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_RISCV_0_DEBUG_INTERFACE 0
#define XPAR_MICROBLAZE_RISCV_0_DEBUG_LATENCY_COUNTERS 0
#define XPAR_MICROBLAZE_RISCV_0_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_RISCV_0_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_MICROBLAZE_RISCV_0_DEBUG_TRACE_SIZE 0
#define XPAR_MICROBLAZE_RISCV_0_DP_AXI_MON 0
#define XPAR_MICROBLAZE_RISCV_0_D_AXI 1
#define XPAR_MICROBLAZE_RISCV_0_D_LMB 1
#define XPAR_MICROBLAZE_RISCV_0_D_LMB_MON 0
#define XPAR_MICROBLAZE_RISCV_0_D_LMB_PROTOCOL 0
#define XPAR_MICROBLAZE_RISCV_0_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_RISCV_0_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_RISCV_0_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_RISCV_0_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_RISCV_0_FREQ 100000000
#define XPAR_MICROBLAZE_RISCV_0_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_RISCV_0_FSL_LINKS 0
#define XPAR_MICROBLAZE_RISCV_0_HARTID 0x0000000000000000
#define XPAR_MICROBLAZE_RISCV_0_IADDR_SIZE 32
#define XPAR_MICROBLAZE_RISCV_0_ICACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_RISCV_0_ICACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_0_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_RISCV_0_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_RISCV_0_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_RISCV_0_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_0_ICACHE_STREAMS 0
#define XPAR_MICROBLAZE_RISCV_0_ICACHE_VICTIMS 0
#define XPAR_MICROBLAZE_RISCV_0_IC_AXI_MON 0
#define XPAR_MICROBLAZE_RISCV_0_ILL_INSTR_EXCEPTION 2
#define XPAR_MICROBLAZE_RISCV_0_IMPID 0x0000000000000001
#define XPAR_MICROBLAZE_RISCV_0_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_RISCV_0_INSTR_SIZE 32
#define XPAR_MICROBLAZE_RISCV_0_INTERCONNECT 2
#define XPAR_MICROBLAZE_RISCV_0_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_RISCV_0_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_RISCV_0_IP_AXI_MON 0
#define XPAR_MICROBLAZE_RISCV_0_I_AXI 0
#define XPAR_MICROBLAZE_RISCV_0_I_LMB 1
#define XPAR_MICROBLAZE_RISCV_0_I_LMB_MON 0
#define XPAR_MICROBLAZE_RISCV_0_I_LMB_PROTOCOL 0
#define XPAR_MICROBLAZE_RISCV_0_LMB_DATA_SIZE 32
#define XPAR_MICROBLAZE_RISCV_0_LOCKSTEP_MASTER 0
#define XPAR_MICROBLAZE_RISCV_0_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_RISCV_0_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_RISCV_0_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_MISALIGNED_EXCEPTIONS 1
#define XPAR_MICROBLAZE_RISCV_0_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_D_BUS_EXCEPTION 1
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_0_M_AXI_I_BUS_EXCEPTION 1
#define XPAR_MICROBLAZE_RISCV_0_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_RISCV_0_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_RISCV_0_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_RISCV_0_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_RISCV_0_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_RISCV_0_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_RISCV_0_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_RISCV_0_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_MICROBLAZE_RISCV_0_OPTIMIZATION 0
#define XPAR_MICROBLAZE_RISCV_0_PART xc7a100tcsg324-1
#define XPAR_MICROBLAZE_RISCV_0_PC_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_PDADDR_SIZE 32
#define XPAR_MICROBLAZE_RISCV_0_PIADDR_SIZE 32
#define XPAR_MICROBLAZE_RISCV_0_PMP_ENTRIES 0
#define XPAR_MICROBLAZE_RISCV_0_PMP_GRANULARITY 2
#define XPAR_MICROBLAZE_RISCV_0_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_0_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_0_TEMPORAL_DEPTH 0
#define XPAR_MICROBLAZE_RISCV_0_TRACE 0
#define XPAR_MICROBLAZE_RISCV_0_USE_ATOMIC 0
#define XPAR_MICROBLAZE_RISCV_0_USE_BARREL 1
#define XPAR_MICROBLAZE_RISCV_0_USE_BITMAN 0
#define XPAR_MICROBLAZE_RISCV_0_USE_BITMAN_A 0
#define XPAR_MICROBLAZE_RISCV_0_USE_BITMAN_B 0
#define XPAR_MICROBLAZE_RISCV_0_USE_BITMAN_C 0
#define XPAR_MICROBLAZE_RISCV_0_USE_BITMAN_S 0
#define XPAR_MICROBLAZE_RISCV_0_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_RISCV_0_USE_COMPRESSION 0
#define XPAR_MICROBLAZE_RISCV_0_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_RISCV_0_USE_COUNTERS 1
#define XPAR_MICROBLAZE_RISCV_0_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_0_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_RISCV_0_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_RISCV_0_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_RISCV_0_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_0_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_0_USE_INTERRUPT 0
#define XPAR_MICROBLAZE_RISCV_0_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_0_USE_MULDIV 0
#define XPAR_MICROBLAZE_RISCV_0_USE_NON_SECURE 0
#define XPAR_MICROBLAZE_RISCV_0_USE_SLEEP 0
#define XPAR_MICROBLAZE_RISCV_0_COMPONENT_NAME system_microblaze_riscv_0_0
#define XPAR_MICROBLAZE_RISCV_0_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_RISCV_0_EDK_SPECIAL microblaze_riscv
#define XPAR_MICROBLAZE_RISCV_0_G_TEMPLATE_LIST 0

/******************************************************************/

#define XPAR_CPU_ID 0
#define XPAR_MICROBLAZE_RISCV_ID 0
#define XPAR_MICROBLAZE_RISCV_ADDR_SIZE 32
#define XPAR_MICROBLAZE_RISCV_ARCHID 0x0000000000000001
#define XPAR_MICROBLAZE_RISCV_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_RISCV_ASYNC_WAKEUP 3
#define XPAR_MICROBLAZE_RISCV_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_RISCV_BASE_VECTORS 0x0000000000000000
#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_RISCV_DADDR_SIZE 32
#define XPAR_MICROBLAZE_RISCV_DATA_SIZE 32
#define XPAR_MICROBLAZE_RISCV_DCACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_VICTIMS 0
#define XPAR_MICROBLAZE_RISCV_DC_AXI_MON 0
#define XPAR_MICROBLAZE_RISCV_DEBUG_COUNTER_WIDTH 64
#define XPAR_MICROBLAZE_RISCV_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_RISCV_DEBUG_EVENT_COUNTERS 0
#define XPAR_MICROBLAZE_RISCV_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_RISCV_DEBUG_INTERFACE 0
#define XPAR_MICROBLAZE_RISCV_DEBUG_LATENCY_COUNTERS 0
#define XPAR_MICROBLAZE_RISCV_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_RISCV_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_MICROBLAZE_RISCV_DEBUG_TRACE_SIZE 0
#define XPAR_MICROBLAZE_RISCV_DP_AXI_MON 0
#define XPAR_MICROBLAZE_RISCV_D_AXI 1
#define XPAR_MICROBLAZE_RISCV_D_LMB 1
#define XPAR_MICROBLAZE_RISCV_D_LMB_MON 0
#define XPAR_MICROBLAZE_RISCV_D_LMB_PROTOCOL 0
#define XPAR_MICROBLAZE_RISCV_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_RISCV_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_RISCV_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_RISCV_FREQ 100000000
#define XPAR_MICROBLAZE_RISCV_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_RISCV_FSL_LINKS 0
#define XPAR_MICROBLAZE_RISCV_HARTID 0x0000000000000000
#define XPAR_MICROBLAZE_RISCV_IADDR_SIZE 32
#define XPAR_MICROBLAZE_RISCV_ICACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_RISCV_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_RISCV_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_ICACHE_STREAMS 0
#define XPAR_MICROBLAZE_RISCV_ICACHE_VICTIMS 0
#define XPAR_MICROBLAZE_RISCV_IC_AXI_MON 0
#define XPAR_MICROBLAZE_RISCV_ILL_INSTR_EXCEPTION 2
#define XPAR_MICROBLAZE_RISCV_IMPID 0x0000000000000001
#define XPAR_MICROBLAZE_RISCV_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_RISCV_INSTR_SIZE 32
#define XPAR_MICROBLAZE_RISCV_INTERCONNECT 2
#define XPAR_MICROBLAZE_RISCV_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_RISCV_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_RISCV_IP_AXI_MON 0
#define XPAR_MICROBLAZE_RISCV_I_AXI 0
#define XPAR_MICROBLAZE_RISCV_I_LMB 1
#define XPAR_MICROBLAZE_RISCV_I_LMB_MON 0
#define XPAR_MICROBLAZE_RISCV_I_LMB_PROTOCOL 0
#define XPAR_MICROBLAZE_RISCV_LMB_DATA_SIZE 32
#define XPAR_MICROBLAZE_RISCV_LOCKSTEP_MASTER 0
#define XPAR_MICROBLAZE_RISCV_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_RISCV_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_RISCV_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_MISALIGNED_EXCEPTIONS 1
#define XPAR_MICROBLAZE_RISCV_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_RISCV_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_RISCV_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_RISCV_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_RISCV_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_RISCV_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_RISCV_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_RISCV_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_M_AXI_D_BUS_EXCEPTION 1
#define XPAR_MICROBLAZE_RISCV_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_RISCV_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_RISCV_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_RISCV_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_RISCV_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_RISCV_M_AXI_I_BUS_EXCEPTION 1
#define XPAR_MICROBLAZE_RISCV_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_RISCV_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_RISCV_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_RISCV_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_RISCV_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_RISCV_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_RISCV_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_RISCV_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_MICROBLAZE_RISCV_OPTIMIZATION 0
#define XPAR_MICROBLAZE_RISCV_PART xc7a100tcsg324-1
#define XPAR_MICROBLAZE_RISCV_PC_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_PDADDR_SIZE 32
#define XPAR_MICROBLAZE_RISCV_PIADDR_SIZE 32
#define XPAR_MICROBLAZE_RISCV_PMP_ENTRIES 0
#define XPAR_MICROBLAZE_RISCV_PMP_GRANULARITY 2
#define XPAR_MICROBLAZE_RISCV_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_RISCV_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_RISCV_TEMPORAL_DEPTH 0
#define XPAR_MICROBLAZE_RISCV_TRACE 0
#define XPAR_MICROBLAZE_RISCV_USE_ATOMIC 0
#define XPAR_MICROBLAZE_RISCV_USE_BARREL 1
#define XPAR_MICROBLAZE_RISCV_USE_BITMAN 0
#define XPAR_MICROBLAZE_RISCV_USE_BITMAN_A 0
#define XPAR_MICROBLAZE_RISCV_USE_BITMAN_B 0
#define XPAR_MICROBLAZE_RISCV_USE_BITMAN_C 0
#define XPAR_MICROBLAZE_RISCV_USE_BITMAN_S 0
#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_COMPRESSION 0
#define XPAR_MICROBLAZE_RISCV_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_RISCV_USE_COUNTERS 1
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_RISCV_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_RISCV_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_INTERRUPT 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_MULDIV 0
#define XPAR_MICROBLAZE_RISCV_USE_NON_SECURE 0
#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0
#define XPAR_MICROBLAZE_RISCV_COMPONENT_NAME system_microblaze_riscv_0_0
#define XPAR_MICROBLAZE_RISCV_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_RISCV_EDK_SPECIAL microblaze_riscv
#define XPAR_MICROBLAZE_RISCV_G_TEMPLATE_LIST 0

/******************************************************************/

#define STDIN_BASEADDRESS 0x40600000
#define STDOUT_BASEADDRESS 0x40600000

/******************************************************************/

/* Platform specific definitions */
#define PLATFORM_RISCV
 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 2U

/* Definitions for peripheral MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 32U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 2U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x00000000U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x0001FFFFU
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID 1U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DATA_WIDTH 32U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_FAULT_INJECT 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_WRITE_ACCESS 2U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_BASEADDR 0x00000000U
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_HIGHADDR 0x0001FFFFU
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/******************************************************************/

/* Canonical definitions for peripheral MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_0_DEVICE_ID XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32U
#define XPAR_BRAM_0_ECC 0U
#define XPAR_BRAM_0_FAULT_INJECT 0U
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_0_WRITE_ACCESS 2U
#define XPAR_BRAM_0_BASEADDR 0x00000000U
#define XPAR_BRAM_0_HIGHADDR 0x0001FFFFU
#define XPAR_BRAM_0_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_0_CTRL_HIGHADDR 0xFFFFFFFEU  
#define XPAR_DLMB_0_CNTLR_BASEADDR 0x00000000
#define XPAR_DLMB_0_CNTLR_HIGHADDR 0x0001FFFF
#define XPAR_DLMB_CNTLR_BASEADDR XPAR_DLMB_0_CNTLR_BASEADDR
#define XPAR_DLMB_CNTLR_HIGHADDR XPAR_DLMB_0_CNTLR_HIGHADDR

/* Canonical definitions for peripheral MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_1_DEVICE_ID XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_1_DATA_WIDTH 32U
#define XPAR_BRAM_1_ECC 0U
#define XPAR_BRAM_1_FAULT_INJECT 0U
#define XPAR_BRAM_1_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_1_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_1_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_1_WRITE_ACCESS 2U
#define XPAR_BRAM_1_BASEADDR 0x00000000U
#define XPAR_BRAM_1_HIGHADDR 0x0001FFFFU
#define XPAR_BRAM_1_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_1_CTRL_HIGHADDR 0xFFFFFFFEU  
#define XPAR_ILMB_0_CNTLR_BASEADDR 0x00000000
#define XPAR_ILMB_0_CNTLR_HIGHADDR 0x0001FFFF
#define XPAR_ILMB_CNTLR_BASEADDR XPAR_ILMB_0_CNTLR_BASEADDR
#define XPAR_ILMB_CNTLR_HIGHADDR XPAR_ILMB_0_CNTLR_HIGHADDR


/******************************************************************/


/* Peripheral Definitions for peripheral VIDEO_VRAM_AXI_CORE_0 */
#define XPAR_VIDEO_VRAM_AXI_CORE_0_BASEADDR 0x00020000
#define XPAR_VIDEO_VRAM_AXI_CORE_0_HIGHADDR 0x0003FFFF


/******************************************************************/




/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 1

/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x4000FFFF
#define XPAR_AXI_GPIO_0_DEVICE_ID 0
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_AXI_GPIO_0_IS_DUAL 0


/******************************************************************/

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_GPIO_0_BASEADDR 0x40000000
#define XPAR_GPIO_0_HIGHADDR 0x4000FFFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_AXI_GPIO_0_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_GPIO_0_IS_DUAL 0


/******************************************************************/

/* Definitions for driver MIG_7SERIES */
#define XPAR_XMIG7SERIES_NUM_INSTANCES 1U

/* Definitions for peripheral MIG_7SERIES_0 */
#define XPAR_MIG_7SERIES_0_DEVICE_ID 0U
#define XPAR_MIG_7SERIES_0_DDR2_ROW_WIDTH 13U
#define XPAR_MIG_7SERIES_0_DDR2_COL_WIDTH 0U
#define XPAR_MIG_7SERIES_0_DDR2_BANK_WIDTH 3U
#define XPAR_MIG_7SERIES_0_DDR2_DQ_WIDTH 16U


/******************************************************************/


/* Definitions for peripheral MIG_7SERIES_0 */
#define XPAR_MIG_7SERIES_0_BASEADDR 0x80000000
#define XPAR_MIG_7SERIES_0_HIGHADDR 0x87FFFFFF


/******************************************************************/

/* Canonical definitions for peripheral MIG_7SERIES_0 */
#define XPAR_MIG7SERIES_0_DEVICE_ID XPAR_MIG_7SERIES_0_DEVICE_ID
#define XPAR_MIG7SERIES_0_DDR_ROW_WIDTH 13U
#define XPAR_MIG7SERIES_0_DDR_COL_WIDTH 0U
#define XPAR_MIG7SERIES_0_DDR_BANK_WIDTH 3U
#define XPAR_MIG7SERIES_0_DDR_DQ_WIDTH 16U
#define XPAR_MIG7SERIES_0_BASEADDR 0x80000000U
#define XPAR_MIG7SERIES_0_HIGHADDR 0x87FFFFFFU


/******************************************************************/

/* Definitions for driver SPI */
#define XPAR_XSPI_NUM_INSTANCES 2U

/* Definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_AXI_QUAD_SPI_0_DEVICE_ID 0U
#define XPAR_AXI_QUAD_SPI_0_BASEADDR 0x44A00000U
#define XPAR_AXI_QUAD_SPI_0_HIGHADDR 0x44A0FFFFU
#define XPAR_AXI_QUAD_SPI_0_FIFO_EXIST 1U
#define XPAR_AXI_QUAD_SPI_0_FIFO_DEPTH 16U
#define XPAR_AXI_QUAD_SPI_0_SPI_SLAVE_ONLY 0U
#define XPAR_AXI_QUAD_SPI_0_NUM_SS_BITS 1U
#define XPAR_AXI_QUAD_SPI_0_NUM_TRANSFER_BITS 8U
#define XPAR_AXI_QUAD_SPI_0_SPI_MODE 0U
#define XPAR_AXI_QUAD_SPI_0_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_AXI_QUAD_SPI_0_AXI4_BASEADDR 0U
#define XPAR_AXI_QUAD_SPI_0_AXI4_HIGHADDR 0U
#define XPAR_AXI_QUAD_SPI_0_XIP_MODE 0U

/* Canonical definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_SPI_0_DEVICE_ID 0U
#define XPAR_SPI_0_BASEADDR 0x44A00000U
#define XPAR_SPI_0_HIGHADDR 0x44A0FFFFU
#define XPAR_SPI_0_FIFO_EXIST 1U
#define XPAR_SPI_0_FIFO_DEPTH 16U
#define XPAR_SPI_0_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_0_NUM_SS_BITS 1U
#define XPAR_SPI_0_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_0_SPI_MODE 0U
#define XPAR_SPI_0_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_SPI_0_AXI4_BASEADDR 0U
#define XPAR_SPI_0_AXI4_HIGHADDR 0U
#define XPAR_SPI_0_XIP_MODE 0U
#define XPAR_SPI_0_USE_STARTUP 0U



/* Definitions for peripheral AXI_QUAD_SPI_1 */
#define XPAR_AXI_QUAD_SPI_1_DEVICE_ID 1U
#define XPAR_AXI_QUAD_SPI_1_BASEADDR 0x44B00000U
#define XPAR_AXI_QUAD_SPI_1_HIGHADDR 0x44B0FFFFU
#define XPAR_AXI_QUAD_SPI_1_FIFO_EXIST 1U
#define XPAR_AXI_QUAD_SPI_1_FIFO_DEPTH 16U
#define XPAR_AXI_QUAD_SPI_1_SPI_SLAVE_ONLY 0U
#define XPAR_AXI_QUAD_SPI_1_NUM_SS_BITS 1U
#define XPAR_AXI_QUAD_SPI_1_NUM_TRANSFER_BITS 8U
#define XPAR_AXI_QUAD_SPI_1_SPI_MODE 0U
#define XPAR_AXI_QUAD_SPI_1_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_AXI_QUAD_SPI_1_AXI4_BASEADDR 0U
#define XPAR_AXI_QUAD_SPI_1_AXI4_HIGHADDR 0U
#define XPAR_AXI_QUAD_SPI_1_XIP_MODE 0U

/* Canonical definitions for peripheral AXI_QUAD_SPI_1 */
#define XPAR_SPI_1_DEVICE_ID 1U
#define XPAR_SPI_1_BASEADDR 0x44B00000U
#define XPAR_SPI_1_HIGHADDR 0x44B0FFFFU
#define XPAR_SPI_1_FIFO_EXIST 1U
#define XPAR_SPI_1_FIFO_DEPTH 16U
#define XPAR_SPI_1_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_1_NUM_SS_BITS 1U
#define XPAR_SPI_1_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_1_SPI_MODE 0U
#define XPAR_SPI_1_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_SPI_1_AXI4_BASEADDR 0U
#define XPAR_SPI_1_AXI4_HIGHADDR 0U
#define XPAR_SPI_1_XIP_MODE 0U
#define XPAR_SPI_1_USE_STARTUP 0U



/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1U

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_DEVICE_ID 0U
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000U
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060FFFFU
#define XPAR_AXI_UARTLITE_0_BAUDRATE 115200U
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0U
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0U
#define XPAR_AXI_UARTLITE_0_DATA_BITS 8U

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_UARTLITE_0_DEVICE_ID 0U
#define XPAR_UARTLITE_0_BASEADDR 0x40600000U
#define XPAR_UARTLITE_0_HIGHADDR 0x4060FFFFU
#define XPAR_UARTLITE_0_BAUDRATE 115200U
#define XPAR_UARTLITE_0_USE_PARITY 0U
#define XPAR_UARTLITE_0_ODD_PARITY 0U
#define XPAR_UARTLITE_0_DATA_BITS 8U


/******************************************************************/
#endif  /* end of protection macro */
